# Your workflow name
name: Primeiro workflow com GitHub Actions 🚀

# Run workflow on every push to main branch
# Reference: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches: [ main ]

# Your workflows jobs
# Reference: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobs
jobs:

  build-and-push:
    runs-on: ubuntu-latest
    
    steps:

      - name: Executar commandos linux
        run: |
          AGORA=`date +%Y/%m/%d-%H:%M:%S`
          echo "date ===> $AGORA"
          echo "hostname ===> `hostname`"
          echo "github.actor ===> ${{ github.actor }}"
          echo "github.event_name ===> ${{ github.event_name }}"
          echo "github.ref ===> ${{ github.ref }}"
          echo "github.repository ===> ${{ github.repository }}"
          echo "github.repository_owner ===> ${{ github.repository_owner }}"
          echo "github.workspace ===> ${{ github.workspace }}"
          echo "github.run_number ===> ${{ github.run_number }}"
          echo "runner / runner.os / runner.name / runner.arch / runner.temp / runner.tool_cache / runner.environment"
          echo "===> ${{ runner }} / ${{ runner.os }} / ${{ runner.name }} / ${{ runner.arch }} / ${{ runner.temp }} / ${{ runner.tool_cache }} / ${{ runner.environment }}"
          echo "pwd ===> `pwd`"
          echo "id ===>`id`"
          echo "df -hT / ===> "; df -hT /
          ls -la /
          echo "======================================================"
          cat /etc/os-release
          echo "======================================================"
          which apt 2>/dev/null || echo "NOT apt"
          which dnf 2>/dev/null || echo "NOT dnf"
          which apk 2>/dev/null || echo "NOT apk"
          which docker 2>/dev/null || echo "NOT docker"
          which git 2>/dev/null || echo "NOT git"

      - name: Mostra variáveis de ambiente
        run: |
          echo "======================================================"
          env
          echo "======================================================"

      - name: Checkout do repositório de código
        uses: actions/checkout@v4

      - name: Build & push Docker - linux/amd64
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
            image: jarbelix/asterisk-ubuntu
            tags: v1,latest
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
      # # Multi-plataform image - https://docs.docker.com/build/ci/github-actions/multi-platform/
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # # Login no Docker Hub
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # # Constroi imagem e armazena no docker hub
      # - name: Build and push - linux/arm64
      #   uses: docker/build-push-action@v6
      #   with:
      #     platforms: linux/arm64
      #     push: true
      #     tags: jarbelix/asterisk-ubuntu:latest, jarbelix/asterisk-ubuntu:v1.${{ github.run_number }}

  novos-comands-linux:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Execute commandos linux finais
        run: |
          AGORA=`date +%Y/%m/%d-%H:%M:%S`
          echo "date ===> $AGORA"
          echo "======================================================"
          cat /etc/os-release
          echo "======================================================"
